version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - backend
    ports:
      - "5432:5432"
  manager:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - backend
    environment:
      - POSTGRES_DSN=postgresql://postgres:password@postgres:5432
      - FUNCTION=create

networks:
  backend:
